version: '3.3'

services:
  labelstudio:
    image: heartexlabs/label-studio:latest
    container_name: labelstudio
    ports:
      - "8080:8080"
    volumes:
      - ./labelstudio-data:/label-studio/data
      - ./myfiles:/label-studio/myfiles
    environment:
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/myfiles
